version: 2.0

shared: &shared
  steps:
    - run:
        name: "Show Node Environment"
        command: 'echo "node: $(node -v)" && echo "npm:  v$(npm -v)"'
    - checkout
    - run: npm install
    - run: npm run lint
    - run: npm run prettier
    - run:
        name: Provide an .env:ironment
        command: base64 -d <<< "$TEST_CONFIG" > .test_config.json
        working_directory: packages/api-tests
    - run: npm test

jobs:
  "node-10":
    <<: *shared
    docker:
      - image: circleci/node:10

workflows:
  version: 2
  build:
    jobs:
      - "node-10"
